#!/bin/bash

# HANDs


# "project-gen" for HH


#mkdirs
mkdir $1



# files

echo -e "# $1\n">README.md


# git

git init
echo -e "[user]\n\tname = xxxxx\n\temail = xxxxxx">$1/.git/config
git add -A
git commit -am init

